/* The fifty reasons, verbatim and in the order Oliver and his sister approved
 * (source of truth: the final wording doc). Do not reword or reorder — the
 * numbering shown on screen is just this array's index + 1. */

export const REASONS = [
  "Because you always always always have the thing we need in your bag",
  "Because you remember every birthday, every year",
  "Because you're impossible to embarrass",
  "Because you get excited about small things",
  "Because purple suited you before anyone told you it did",
  "Because everything you love, you love properly",
  "Because you love K-pop unapologetically and we love you for it",
  "Because you make ordinary days feel like something",
  "Because you can tell when we're lying and you let us finish anyway",
  "Because your advice is annoying and correct",
  "Because you argue with us because you care, not because you're right",
  "Because you say the hard thing when everyone else is being polite",
  "Because you'd rather be honest than liked, and somehow you're both",
  "Because you never pretend to be someone you're not",
  "Because you're stubborn, and it's saved this family more than once",
  "Because you're the one who remembers what everyone else forgets",
  "Because you're the first person either of us calls",
  "Because you know when something's wrong before we say a word",
  "Because you always answer, even when you're busy",
  "Because the house is different when you're not in it",
  "Because you're the reason we all still gather",
  "Because you kept our traditions alive when it would have been easier to let them go",
  "Because you made sure we knew where we come from",
  "Because you honour the people who came before us",
  "Because you made being Chinese something we're proud of, not something we explain",
  "Because you work harder than anyone and never mention it",
  "Because you never let us settle for the easy version of ourselves",
  "Because you gave up things we'll never fully know about",
  "Because you've earned every good thing you have",
  "Because you never asked us to be grateful, and we are anyway",
  "Because you were strict for exactly the right reasons",
  "Because you said no",
  "Because you said yes",
  "Because your standards made us better even when we hated them",
  "Because you let us make our own mistakes and were there afterwards anyway",
  "Because you never made us feel like we were a burden",
  "Because you believed in us before there was any evidence",
  "Because you taught us how to treat people, mostly by doing it",
  "Because you're the reason we know what a good person looks like",
  "Because you're the person we measure other people against",
  "Because you chose us first, every single time, without making it a story",
  "Because you love us differently and exactly equally",
  "Because you gave us a sibling, which is the best thing you could've done",
  "Because you're proud of who we are, not just what we've done",
  "Because you're proud of us in a way we can feel from across the room",
  "Because we've never once doubted that you love us",
  "Because you gave us a childhood we'd choose again",
  "Because being your kid is the reason we turned out alright",
  "Because everything good about us started with you",
  "Because 50 looks nothing like we were told 50 would look",
];

export const TOTAL = REASONS.length;
